// Default themes use Deezer editorial playlists (stable IDs, 30s previews, no API key needed)
export const THEMES = [
  {
    id: 'fr-hits',
    emoji: '🇫🇷',
    name: 'Hits français',
    description: 'Top hits francophones',
    source: 'deezer',
    playlistId: '1282516004',
  },
  {
    id: 'hiphop-fr',
    emoji: '🎤',
    name: 'Hip-hop FR',
    description: 'Rap et hip-hop français',
    source: 'deezer',
    playlistId: '4232066',
  },
  {
    id: '80s',
    emoji: '🕺',
    name: 'Années 80',
    description: 'Classics pop/rock des années 80',
    source: 'deezer',
    playlistId: '908622995',
  },
  {
    id: 'rock-classic',
    emoji: '🎸',
    name: 'Rock classique',
    description: 'Queen, AC/DC, Nirvana, U2...',
    source: 'deezer',
    playlistId: '1313621735',
  },
  {
    id: 'rnb',
    emoji: '🎵',
    name: 'R&B / Soul',
    description: 'R&B et soul intemporels',
    source: 'deezer',
    playlistId: '1313621735',
  },
  {
    id: 'dance',
    emoji: '💃',
    name: 'Club / Dance',
    description: 'Hits électro et dance',
    source: 'deezer',
    playlistId: '1282516144',
  },
  {
    id: 'pop-world',
    emoji: '🌍',
    name: 'Hits internationaux',
    description: 'Pop mondiale top charts',
    source: 'deezer',
    playlistId: '3155776842',
  },
  {
    id: '90s',
    emoji: '📼',
    name: 'Années 90',
    description: 'Les indémodables des 90s',
    source: 'deezer',
    playlistId: '1282516024',
  },
];
